version: '2.3'


services:
  # unison container
  # mounts the project dir to /mnt/master using a bind mount
  # then replicas are created in a volume replica
  unison:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/mnt/master:delegated
      - replica:/mnt/replica
  # dependent container example
  # this mounts the replica. it is faster than mounting the project dir directly.
  # the files are bidirectionally kept in sync
  mounted:
    image: alpine:latest
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      - unison
    volumes:
      - replica:/mnt/replica
volumes:
  replica: {}
